image: node:14

cache:
  paths:
    - node_modules/

stages:
  - install
  - test
  - image

install_packages:
  stage: install
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

test_backend:
  stage: test
  script:
    - yarn test

build_image:
  stage: image
  image: docker:stable
  services:
    - name: docker:dind
      alias: dockerdaemon
  variables:
    DOCKER_HOST: tcp://dockerdaemon:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login $DOCKER_REGISTRY --username $DOCKER_REGISTRY_USER --password-stdin
  script:
    - docker login -u "gge275" -p "DOCKER_PASSWORD" "hub.docker.com"
    - docker build . -t gge2705/netflix-clone-backend
    - docker push gge2705/netflix-clone-backend