image: node:14

cache:
  paths:
    - node_modules/

stages:
  - install
  - test
  - image

install_packages:
  stage: install
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

test_backend:
  stage: test
  script:
    - yarn test

build_image:
  stage: image
  script:
    - docker build . -t gge2705/netflix-clone-backend
    - docker push gge2705/netflix-clone-backend