image: node:14

cache:
  paths:
    - node_modules/

stages:
  - install
  - test
  - image

install_packages:
  stage: install
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

test_backend:
  stage: test
  script:
    - yarn test

build_image:
  stage: image
  image: docker:19.03.13
  services:
    - docker:19.03.13-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login --username $DOCKER_REGISTRY_USER --password-stdin
  script:
    - docker build . -t gge2705/netflix-clone-backend
    - docker push gge2705/netflix-clone-backend