image: node:14

cache:
  paths:
    - node_modules/

stages:
  - install
  - test

install_packages:
  stage: install
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

test_backend:
  stage: test
  script:
    - yarn test